include: "mgen_preprocess.smk"
include: "gtpro.smk"
include: "sfacts.smk"
include: "midas.smk"
include: "strain_reconstruction.smk"
include: "sfinder.smk"
include: "reference_genome.smk"
include: "pangenome.smk"
