rerun-triggers: ['mtime', 'params', 'input', 'software-env', 'code']
notemp: true
printshellcmds: true
keep-going: true
resources: ['network_connections=3', 'mem_mb=750000']
default-resources:
  - 'pmem=8192'
  - 'disk_mb=100000'
  - 'walltime_hr=0'
  - 'walltime_min=29'
  - 'walltime_sec=59'
  - 'gpu_mem_mb=1000'
  - 'outdir="log/"'
use-conda: true
conda-frontend: 'mamba'
use-singularity: true
singularity-args: >-
  --env CONDA_PKGS_DIRS=$HOME/.snakemake/conda/pkgs
  --nv
  --bind $TMPDIR
  --bind $PWD/include:/include
  --bind /salilab/diva1/home/anaconda/anaconda3
  --bind /pollard
  --bind /wynton
  --bind /scratch
config:
  - 'USE_CUDA=1'
  - 'MAX_THREADS=24'
  - 'jupyter_port=8828'
  - 'server_port=8829'
