rerun-triggers: ['mtime', 'params', 'input']
notemp: true
printshellcmds: true
keep-going: true
latency-wait: 5
resources: ['network_connections=3', 'mem_mb=500000', 'gpu=4']
use-conda: true
conda-prefix: "/pollard/home/bsmith/.snakemake/conda"
conda-frontend: 'mamba'
use-singularity: true
singularity-prefix: "/pollard/home/bsmith/.snakemake/singularity"
singularity-args: >-
  --env CONDA_PKGS_DIRS=$HOME/.snakemake/conda/pkgs
  --nv
  --bind $TMPDIR
  --bind $PWD/include:/include
  --bind /pollard
config:
  - 'USE_CUDA=1'
  - 'MAX_THREADS=24'
  - 'jupyter_port=8818'
  - 'server_port=8819'
